[repository]
name = "tremt"
changelog = "CHANGELOG.md"
version = "version.txt"
compose = ["docker-compose.yml"]

[repository.towncrier]
section = "Project"
settings = "towncrier.toml"

[backend.package]
name = "tremt.site"
path = "backend"
changelog = "backend/CHANGELOG.md"
towncrier_settings = "backend/pyproject.toml"
base_package = "Products.CMFPlone"
publish = false

[frontend.package]
name = "volto-tremt-site"
path = "frontend/packages/volto-tremt-site"
changelog = "frontend/packages/volto-tremt-site/CHANGELOG.md"
towncrier_settings = "frontend/packages/volto-tremt-site/towncrier.toml"
base_package = "@plone/volto"
publish = false

[cookieplone]
template = "project"
template_version = "42ccd46105b33ed1efdd2f97e26da91ff5eedd15"
generated_date = "2025-10-02 13:12:48"
